version: '3.8'

services:
  # Nest.js application
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile # Replace with your actual Dockerfile name
    ports:
      - '3000:3000' # Adjust the ports as needed
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - NODE_ENV=production
      # Add any other environment variables your Nest.js app requires

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3.9
    ports:
      - '5672:5672' # RabbitMQ port
      - '15672:15672' # RabbitMQ management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=your_rabbitmq_user
      - RABBITMQ_DEFAULT_PASS=your_rabbitmq_password

  # PostgreSQL service
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432' # PostgreSQL port
    environment:
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
